DROP TABLE IF EXISTS chart_items;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS charts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;