// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	category "github.com/andreanpradanaa/trendstore/internal/domain/category"
	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the Repository type
type CategoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *CategoryRepository) Create(_a0 *category.Category) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*category.Category) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
