// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	product "github.com/andreanpradanaa/trendstore/internal/domain/product"
	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the Repository type
type ProductRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: args
func (_m *ProductRepository) Create(args *product.Product) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*product.Product) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with no fields
func (_m *ProductRepository) List() ([]product.Product, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]product.Product, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []product.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
